<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading  fondo-gris texto-blanco">
                        <h5 class="panel-title text-center">Registro Mercaderia</h5>
                    </div>
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-xs-3">
                            </div>
                            <div class="col-xs-5">
                                <span class="texto-negro-right">ID Boleta :</span>
                                <input type="text" id="txtIDCita" class="form-control color-yellow texto-negro-cita" placeholder="ID Cita" maxlength="9">
                            </div>
                            <div class="col-xs-3">
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-3">
                            </div>
                            <div class="col-xs-5">
                                <button class="btn btn-info form-control  crear-tooltip" id="btn_consultar" disabled="disabled" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Consultar  --- ">Consultar</button>
                            </div>
                            <div class="col-xs-3">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </section>

    </div>